### PR TITLE
chore: Satisfy clippy and update org name.

### PR DESCRIPTION
**Pull request by ghost**
This PR removes satisfies clippy and updates the organization name in LICENSE and README.md

### CODE REVIEW

**Comment by sammy-ette** [comment]
rs branch isn't maintained

**Comment by devins2518** [comment]
@CoffeeSip add log.txt to your global gitignore

**Comment by ghost** [comment]
> rs branch isn't maintained

why not delete or archive it then

**Comment by devins2518** [comment]
I maintain my own package for my nix repository. It’s faster so I use it. Sammy maintains the go (main) branch.


From,
Devin Singh

**Pull request closed without merging**
